### ISSUE TITLE
Installed is no longer a valid argument for the ansible.builtin.package module

### ISSUE THREAD

**Issue by justin-p** [geerlingguy/ansible-role-firewall#107]
Hi @geerlingguy,

The role currently fails to run. It seems that the package module no longer allows `installed` as a valid state argument.

```
TASK [geerlingguy.firewall : Ensure iptables is installed.] *******************************************************************************************************************
fatal: [honest-moray-sx98z]: FAILED! => {"changed": false, "msg": "value of state must be one of: absent, build-dep, fixed, latest, present, got: installed"}
```

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html

I worked around this issue by changing it to `present`.

**Comment by justin-p** [comment]
nvm, just spotted that the latest tagged version is from 2016. Will use the main branch instead.

Would it be possible to create a new tag ?

**Comment by geerlingguy** [comment]
Latest tag is from 2024... https://github.com/geerlingguy/ansible-role-firewall/tags — are you not seeing that somewhere?

**Comment by justin-p** [comment]
Hia @geerlingguy, I've done goofed, all is fine on your end. It seems I got confused last night because of the release from 2016 that's on the main page. Should have checked better, sorry for the trouble :wink: 
![screenie](https://github.com/geerlingguy/ansible-role-firewall/assets/8249280/9522b6cb-d485-4759-99b8-78344a377c83)

**Comment by geerlingguy** [comment]
Ah no worries then!
