### ISSUE TITLE
Moving `firewall_additional_rules` up or another block of custom rules in the very beginning

### ISSUE THREAD

**Issue by zerkms** [geerlingguy/ansible-role-firewall#12]
I case if it's necessary in having some extra `DROP`s before the open and forwarded ports block it may be helpful to have a `firewall_pre_additional_rules` (or move the additional rules up, if you are sure it won't break anything).

What do you think of it?

**Comment by huglester** [comment]
Hello
would be good idea yes

**Comment by blackstar257** [comment]
Agreed just ran into this.

**Comment by zerkms** [comment]
it's still actual I think
