### ISSUE TITLE
Firewall override by different ansible projects

### ISSUE THREAD

**Issue by tloeb** [geerlingguy/ansible-role-firewall#15]
We devided our ansible project in different parts:
- One Part for dns
- And another Part for netdata

This works pretty well, but each part has a role to add specific firewall settings.
Sadly the configuration is always overwritten so only the last firewall settings will be configured.
Is it possible not to override the whole iptables?

**Comment by geerlingguy** [comment]
@tloeb with the way this role is set up (to be simple and be the only role to control iptables), it won't be possible to have different roles / parts of a playbook control different chunks of iptables. For that, I'd recommend either using Ansible's built-in tooling (with newer OS firewalls), or building a more customized role. This is meant more for use cases where you're only running a few services per server, and all firewall configuration is done via this role.
