### ISSUE TITLE
Can't get firewall working with allowed tcp ports

### ISSUE THREAD

**Issue by relumer** [geerlingguy/ansible-role-firewall#24]
hI
this is my vars/main.yml

cat vars/main.yml 
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
  - "5000"

i added 2 ports

and this is the defaults/main.yml

 cat defaults/main.yml 
---
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
  - "5000"

this is inside the playbook

- hosts: lan
  remote_user: root
  vars_files:
    - vars/main.yml  
  roles:
     - { role: geerlingguy.firewall }

it is my understand that the above ports will be allowed , correct?
The play completes fine with no errors but if i nmap one host like this

 nmap 192.168.1.2

Starting Nmap 7.01 ( https://nmap.org ) at 2016-11-26 00:41 EET
Nmap scan report for 192.168.1.2 Host is up (0.00063s latency).
Not shown: 997 filtered ports
PORT   STATE  SERVICE
22/tcp open   ssh
25/tcp closed smtp
80/tcp open   http

Nmap done: 1 IP address (1 host up) scanned in 4.67 seconds

it does not list the ports i previously added

can you explain why ?
thank you

**Comment by geerlingguy** [comment]
@relumer - `nmap` can be a little tricky... are you able to connect to the services in question (whatever's running on 443 and 5000), or are they being blocked? Can you also [check which services are running on which ports](http://unix.stackexchange.com/a/62249/16194) to confirm that there are, in fact, services listening on those ports (if that's your intention)?

Also, double-check the firewall is set up properly by running `sudo iptables -L` on the box to see if the rules you set applied. You should see 443 and 5000 in there.

**Comment by relumer** [comment]
Hi 
i have noting listening on 443 and 5000 but i was planning to set up services that listen on those ports later on.  
from that host iptables -L shows this

sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:smtp
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     icmp --  anywhere             anywhere            
ACCEPT     udp  --  anywhere             anywhere             udp spt:ntp
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
LOG        all  --  anywhere             anywhere             limit: avg 15/min burst 5 LOG level debug prefix "Dropped by firewall: "
DROP       all  --  anywhere             anywhere            

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             anywhere             udp dpt:ntp


/etc/init.d/firewall status will show these

ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:22
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80


443 and 5000 are not listed. 
What other things should i check .. ?

**Comment by relumer** [comment]
after some trial and errors i have managed to see them listed 

iptables -L -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:22
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:5000


when i believe that 22 25 and 80 should not show up because this is the play these are coming from 

- hosts: lan
  remote_user: root
  vars:
    firewall_allowed_tcp_ports:
      - "443"
      - "5000"
  roles:
    - { role: geerlingguy.firewall }


and nmap shows this

PORT     STATE  SERVICE
22/tcp   open   ssh
25/tcp   closed smtp
80/tcp   open   http
443/tcp  closed https
5000/tcp closed upnp

if this is getting confusing , what i am trying to do is to only have ports 443 and 5000 allowed and nothing else .
If i go ahead and install the services that listen on those ports ( somthing i was going to do later) will this result in port triggering and open 443 and 5000 ? :)

**Comment by geerlingguy** [comment]
@relumer - Try also running `sudo service firewall restart` to manually refresh iptables; it might be that it didn't restart cleanly the first time you ran the playbook...

**Comment by relumer** [comment]
@geerlingguy i just did that but i don't see anything changed

**Comment by relumer** [comment]
@geerlingguy  it seems that no matter what it only works with the ones that come with the code , 22,25 and 80. These are defined in defaults/main.yml   and i have also defined them in vars/main.yml
still though .. are being ignored

have you tested yourself please to allow some others ports to be allowed or denied etc using this?
i believe only the defaults/main.yml and in vars/main.yml must be edited  for this to work

**Comment by geerlingguy** [comment]
@relumer - I use the role for [Drupal VM](https://www.drupalvm.com) and almost all my servers, and can confirm it's working correctly there; I wonder if there's some other place the variable might be defined?

Also, you can do a test play _after_ the role in your playbook, like:

```yaml
- hosts: all
  ...
  roles:
    - geerlingguy.firewall

  tasks:
    - debug: var=firewall_allowed_tcp_ports
```

Then when the playbook runs, you will see exactly the value of the variable Ansible is seeing.

**Comment by relumer** [comment]
@geerlingguy  ok i will try th debug in a while and report back

so , where would you define a port lets say 5000 to be allowed for one [group] ?

**Comment by relumer** [comment]
@geerlingguy ok i did the debug test and here is the output

ok: [lan] => {
    "firewall_allowed_tcp_ports": [
        "22", 
        "25", 
        "80", 
        "443", 
        "5000"
    ]
}

so this allows all ports defined in allowed tcp ports.

i did the nc test and

 nc -zv 192.168.1.2 5000
nc: connect to 192.168.1.2 port 5000 (tcp) failed: Connection refused

for 22 works

nc -zv 192.168.1.2 22
Connection to 192.168.1.2 22 port [tcp/ssh] succeeded!



i will continue looking for way to allow this to deny ports..

**Comment by geerlingguy** [comment]
@relumer - Could there be some other firewall/ip-level blocking happening? From the `iptables -L -n`, it looks like those rules _are_ working as this role intends. Maybe there's something else running on the server or on the network/vlan level that's blocking other ports.

443 is also allowed by default by this role (see https://github.com/geerlingguy/ansible-role-firewall/blob/master/defaults/main.yml#L6), and it seems that port isn't showing with nc/etc.

**Comment by relumer** [comment]
there is no other firewall or ip blocking , they are fresh debian and ubuntu VMs
i still cant understand why nc can not connect to 443 or 5000 @geerlingguy

**Comment by geerlingguy** [comment]
@relumer - I don't think there's any other debugging I can do—I am using the role on multiple Ubuntu 16/14/12, CentOS 6/7, and Debian 8 servers, and haven't encountered any issue with the port open/closed rules, and it looks like `iptables` is configured correctly as this role should be doing, so I can't think of anything else I can do to help...

You can also enable the firewall logging and watch the log file and see what happens when you try connecting to certain ports (try 5001, make sure a log entry shows up, then try 5000 and see if the same happens...).

**Comment by relumer** [comment]
i may have some updates on this issue soon @geerlingguy
