### ISSUE TITLE
Remove forwarding rules at the beginning of the script

### ISSUE THREAD

**Issue by widmoser** [geerlingguy/ansible-role-firewall#25]
When running the role multiple times, the forwarding rules accumulate, because `iptables -F` does not remove them. 

Suggestion: 
`iptables -F -t nat` seems to resolve the issue.

**Comment by geerlingguy** [comment]
Interesting... I hadn't noticed that but haven't looked to closely on the servers where I have forwarding rules. I'll test to verify.
