### ISSUE TITLE
firewall.unit is not supported on RedHat

### ISSUE THREAD

**Issue by asghaier** [geerlingguy/ansible-role-firewall#28]
The task `Ensure the firewall is enabled and will start on boot.` fails on RedHat because the previous step `Copy firewall systemd unit file into place (for systemd systems)` does not copy the firewall.unit file.

Following is the output I get for RHEL7:

```
TASK [geerlingguy.firewall : Copy firewall systemd unit file into place (for systemd systems).] ***
skipping: [192.168.99.100]

TASK [geerlingguy.firewall : Ensure the firewall is enabled and will start on boot.] ***
fatal: [192.168.99.100]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'firewall'\": "}
```

**Comment by geerlingguy** [comment]
Eek, makes sense... I'll review the PR.

**Comment by geerlingguy** [comment]
This was in 2.0.2. Thanks!
