### ISSUE TITLE
Is it possible to allow all traffic from localhost?

### ISSUE THREAD

**Issue by jdart** [geerlingguy/ansible-role-firewall#3]
Is it possible to allow all traffic from localhost to localhost?

**Comment by cstrutton** [comment]
I believe this is already done for you.  See line 36/37 in `templates/firewall.bash.j2`

```
# Accept traffic from loopback interface (localhost).
iptables -A INPUT -i lo -j ACCEPT
```

That does exactly what your asking.

**Comment by geerlingguy** [comment]
@jdart - @cstrutton is correct. Are you having issues making local connections?
