### ISSUE TITLE
Empty allowed ports list leads to all the ports open

### ISSUE THREAD

**Issue by mtpereira** [geerlingguy/ansible-role-firewall#38]
Hello @geerlingguy ,

The `/etc/firewall.bash` script sets a `ACCEPT` policy for all the default chains before setting any rules. This will cause it to have all ports opened by default:

```
$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     icmp --  anywhere             anywhere
ACCEPT     udp  --  anywhere             anywhere             udp spt:ntp
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
DROP       all  --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     udp  --  anywhere             anywhere             udp dpt:ntp

 $ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -p udp -m udp --sport 123 -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -p udp -m udp --dport 123 -j ACCEPT
```

In general, it is a good practice to start an `iptables` setup by `DROP`ping everything on `INPUT` and `FORWARD` and then whitelist whatever you need to, instead of `ACCEPT`ing everything and then blacklisting what you want, because the first is safer by default.

Do you agree with this? I'll PR my changes for this if you agree with this perspective.

Thank you.

**Comment by FloMko** [comment]
@mtpereira 
/etc/firewall.bash
in script i found 

# Completely reset the firewall by removing all rules and chains.
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -F
iptables -t mangle -F
iptables -F
iptables -X

it will flush default rule

**Comment by rhtnr** [comment]
I believe dropping all prior connections like mentioned might make Ansible to lose the SSH connectivity as well

**Comment by mcg** [comment]
Just installed this role and noticed this issue. Think this may be addressed soon?
