### ISSUE TITLE
Disabling firewalls fails on my Ubuntu server

### ISSUE THREAD

**Issue by noplanman** [geerlingguy/ansible-role-firewall#40]
On an Ubuntu server of mine, I get the following error running this role:
`fatal: [0.0.0.0]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service ufw: host"}`

Output for `dpkg -l ufw` (which this role uses to check if it's installed):
```bash
$ sudo dpkg -l ufw
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                               Version                Architecture           Description
+++-==================================-======================-======================-=========================================================================
un  ufw                                <none>                 <none>                 (no description available)
```
This gives a return code of `0`, but I don't have the package installed. It seems that the dpkg cache is queried, resulting in the response being true, as the packed is available for install.

Maybe a better way to check this is to see if the service itself is installed?
```bash
$ service ufw status
● ufw.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```
This correctly returns `1` if not installed, and `0` if it is.

As this is checking the status, it's obviously possible that the service crashed, which may also return `1`, thus being a false result. Not totally sure about this though.

EDIT: Of course I can leave `firewall_disable_ufw` to the default `false`, but I have that variable set for all hosts to make it easier.

**Comment by geerlingguy** [comment]
I just started seeing this on Ubuntu 16.04 today... very strange—it was working in the past!

**Comment by noplanman** [comment]
Ghost in the machine 👻

**Comment by geerlingguy** [comment]
Fixed—I'll tag a new release in a minute... since I need it for my own work today :D
