### ISSUE TITLE
Docker role causes Docker's first start to fail with 'Couldn't load target DOCKER'

### ISSUE THREAD

**Issue by lazzurs** [geerlingguy/ansible-role-firewall#43]
I have installed both this role and the docker role on the same server. After running both when trying to use Docker after this has run I get the following.

```
Creating network "digitalhub_default" with the default driver
ERROR: Failed to program FILTER chain: COMMAND_FAILED: '/usr/sbin/iptables -w2 -I FORWARD -o br-919bc7916019 -j DOCKER' failed: iptables v1.4.21: Couldn't load target `DOCKER':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
```

Restarting the Docker service puts the rules back into place and Docker starts working again.

I think from this module either having a flag to ignore the Docker rules or a post change command to allow the Docker service to be restarted would be useful.

**Comment by geerlingguy** [comment]
I hit the same issue, and have to restart Docker to get it working... not sure what's the best approach here, but I know that I see Docker having weird issues with iptables in many other scenarios too. It might be better to fix things in the Docker role instead.

**Comment by geerlingguy** [comment]
See related: https://github.com/geerlingguy/ansible-role-docker/issues/21

**Comment by geerlingguy** [comment]
This is fixed by the `geerlingguy.docker` role version 2.2.0, and to make sure it works in your playbook, please make sure to have the `geerlingguy.firewall` role run _before_ the `geerlingguy.docker` role.
