### ISSUE TITLE
Fails on install at "Flush iptables the first time playbook runs."

### ISSUE THREAD

**Issue by linuxsoftware** [geerlingguy/ansible-role-firewall#5]
Using Ansible 1.8.2 from Fedora 19 to set up Centos 6.6.

I found when I tried to run a playbook with this role it would fail on the "Flush iptables the first time playbook runs" task with a file not found error, and then not go on to actually install the service.  My fix was to add "ignore_errors: yes" for that task.

I am very new to Ansible, so it may be something to do with my setup.  Hope this is of some use to someone.

**Comment by geerlingguy** [comment]
Can you paste the output from the playbook run here, so it's easier to debug what's going on? I have a feeling this may be related to #2.

**Comment by linuxsoftware** [comment]
Sure.

```
$ ansible-playbook --ask-su-pass jsite.yml -v
su password: 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [software.gen.nz]

TASK: [firewall | Ensure iptables is installed (RedHat).] ********************* 
ok: [software.gen.nz] => {"changed": false, "msg": "", "rc": 0, "results": ["iptables-1.4.7-14.el6.x86_64 providing iptables is already installed"]}

TASK: [firewall | Ensure iptables is installed (Debian).] ********************* 
skipping: [software.gen.nz]

TASK: [firewall | Flush iptables the first time playbook runs.] *************** 
failed: [software.gen.nz] => {"cmd": "iptables -F", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/djm/jsite.retry

software.gen.nz            : ok=2    changed=0    unreachable=0    failed=1   
```

**Comment by geerlingguy** [comment]
My guess is that `iptables-service` is not installed (I'm fuzzy on when the switch to `firewalld` happened in Fedora)... I'll try to do some testing on CentOS 7 as well to see what's happening.

See: http://stackoverflow.com/a/24827438/100134

**Comment by geerlingguy** [comment]
I just ran the playbook on a couple fresh instances of CentOS 6 and CentOS 7 without any issues, so I'm guessing the image you were building on had something different about it (likely `iptables-service` wasn't installed or something like that).

If you can replicate, please try logging in before running the playbook and running the command `$ sudo iptables -L` and see what happens.

Going to close the issue for now, since I can't replicate. But we can reopen if we find a deeper issue.

**Comment by linuxsoftware** [comment]
No worries.  Adding the ignore_errors: yes flag was a simple fix.  Maybe Ansible has changed how it regards tasks that say they will create a file, but then don't?

Thanks for sharing this role.

**Comment by geerlingguy** [comment]
No problem!

**Comment by JasmineYuan** [comment]
This problem also came to me when I use Ansible 1.9.0.1 from mac to set up Centos 6.6

**Comment by geerlingguy** [comment]
@JasmineYuan - Can you run the command `sudo iptables -L` from inside the CentOS 6.6 machine and see what happens?

**Comment by JasmineYuan** [comment]
This is the result:
![screen shot 2015-04-04 at 10 10 57 am](https://cloud.githubusercontent.com/assets/8992254/6991071/efdf4284-dab2-11e4-8ab3-3bed73aabe91.png)

**Comment by geerlingguy** [comment]
@JasmineYuan when you run your ansible playbook, do you run it as a sudo user or with `sudo: yes` in the playbook? If not, try doing that—and if you don't want to run the whole playbook as sudo, try running the firewall role as sudo (e.g. the below example):

``` yaml
  roles:
    - { role: geerlingguy.firewall, sudo: yes }
```

**Comment by JasmineYuan** [comment]
Yes, I did run as a sudo user, below is where I use geerlingguy.firewall: 
![screen shot 2015-04-04 at 10 41 16 am](https://cloud.githubusercontent.com/assets/8992254/6991174/353a98e8-dab7-11e4-8d54-535735eba788.png)

**Comment by JasmineYuan** [comment]
@geerlingguy Seems it's a bug of ansible 1.9.0.1, sudo: yes can not executed correctly. It's ok to use ansible 1.8.4.

**Comment by joustava** [comment]
I am running this role from the nodejs examples, but in my case I am also trying out to run it in a docker container. I get a similar error message:

```
ASK: [geerlingguy.firewall | Flush iptables the first time playbook runs.] ***
failed: [localhost] => {"changed": true, "cmd": ["iptables", "-F"], "delta": "0:00:00.034790", "end": "2015-   06-11 10:02:07.715212", "rc": 3, "start": "2015-06-11 10:02:07.680422", "warnings": []}
stderr: iptables v1.4.21: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/playbook.retry

localhost                  : ok=3    changed=1    unreachable=0    failed=1
```

I tried both a 'global' root: yes and the root setting on the role itself as you proposed above. Still the same error. 

host: mac
vm: ubuntu
ansible 1.9.1
