### ISSUE TITLE
ip6tables rule is allowing wrong version of ICMP

### ISSUE THREAD

**Issue by smveloso** [geerlingguy/ansible-role-firewall#54]
A rule exists to allow ICMP for IPv6. That's necessary and is OK.
However, it's allowing ICMP for IPv4.

In file _firewall.bash.j2_:

`# Accept icmp ping requests.`
`ip6tables -A INPUT -p icmp -j ACCEPT`

It should be **-p icmpv6** or **-p ipv6-icmp**. Not sure, it seems both forms are acceptable (and worked for me).

**Comment by mcg** [comment]
Looks like #44 has been around for a long time to fix this. Is this repo dead?

**Comment by lazzurs** [comment]
@geerlingguy given the repo clearly isn't dead this looks like a simple fix to accept. Is this something you are still working on or should it be forked to accept this fix?

**Comment by lazzurs** [comment]
I have fixed this on my systems for now allowing some time for an answer with adding the following to the vars.

firewall_ip6_additional_rules:
  - "ip6tables -A INPUT -p icmpv6 -j ACCEPT"

**Comment by geerlingguy** [comment]
This has been fixed via https://github.com/geerlingguy/ansible-role-firewall/pull/44

Thanks!
