### ISSUE TITLE
UDP Rules are not working

### ISSUE THREAD

**Issue by jkomara** [geerlingguy/ansible-role-firewall#6]
In firewall.bash.j2 for UDP rules it has:

{% for port in firewall_allowed_udp_ports %}
iptables -A INPUT -p tcp -m udp --dport {{ port }} -j ACCEPT
{% endfor %}

It should be:

{% for port in firewall_allowed_udp_ports %}
iptables -A INPUT -p udp -m udp --dport {{ port }} -j ACCEPT
{% endfor %}

Once I changed -p to udp it worked.

Thanks.

**Comment by geerlingguy** [comment]
@jkomara - Good catch, thanks for reporting this!
