### ISSUE TITLE
how to open port for OUTPUT dns ?

### ISSUE THREAD

**Issue by rubendob** [geerlingguy/ansible-role-firewall#7]
hi!

firstable, I love your job with Ansible, I think is very helpful. 

About this role, I don't know how to tell firewalls to open port for OUTPUT chain and port 53... 

The problem is my machine can resolv domain names with the firewall activated.

Thanks!

**Comment by rubendob** [comment]
Hi! 

the problem is that the rules to allow INPUT are always setup after DROP

LOG        all  --  0.0.0.0/0            0.0.0.0/0            limit: avg 15/min burst 5 LOG flags 0 level 7 prefix "Dropped by firewall: "
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp spt:53
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp spt:53

It is normal? Maybe I'm doing something wrong ?

Thanks

**Comment by rubendob** [comment]
My current config:

target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:smtp
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     icmp --  anywhere             anywhere
ACCEPT     udp  --  anywhere             anywhere             udp spt:ntp
LOG        all  --  anywhere             anywhere             limit: avg 15/min burst 5 LOG level debug prefix "Dropped by firewall: "
DROP       all  --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     udp  --  anywhere             anywhere             udp dpt:ntp
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain

the firewall avoid host to resolv domain names.... any comment?

Thanks!

**Comment by rubendob** [comment]
Sorry jeff

after some R+D I noticed was a issue with openvz.

Thanks!

**Comment by geerlingguy** [comment]
Great! Glad you could find the problem, and sorry for not responding sooner!
