### ISSUE TITLE
Flushing iptables on first run is causing ssh lockdown

### ISSUE THREAD

**Issue by sid255** [geerlingguy/ansible-role-firewall#88]
When I run this role on my remote servers, the first task of flushing iptables is causing ssh lockdown and disconnection. I had to add the default rules task before flushing to make it work. Is this normal behavior or am I doing something wrong?

**Comment by shk3bq4d** [comment]
`iptables -F`

present both in:
* [tasks/main.yml](https://github.com/geerlingguy/ansible-role-firewall/blob/727e3dae18a1a96227249e2cbb1808d53465dd1a/tasks/main.yml#L7)
* [systemd unit file](https://github.com/geerlingguy/ansible-role-firewall/blob/727e3dae18a1a96227249e2cbb1808d53465dd1a/templates/firewall.unit.j2#L8)

is a command to never execute when your chains policies are different from ACCEPT. Can you confirm this is your case @sid255 ?

Maybe supporting a configurable default var `firewall_flush_commands` that defaults to current `iptables -F` with a README note that proposes to execute the following consecutive commands

`iptables -w 45 -P INPUT   ACCEPT; iptables -w 45 -P FORWARD ACCEPT; iptables -w 45 -P OUTPUT  ACCEPT; iptables -w 45 -F`

as a proposal for people in this situation would solve the problem?

edit: merge request #87, aiming to solve the specific case of interaction with docker daemon managed rules mentioned in #82,  has an alternative proposal to disable the initial flush and systemd ExecStop altogether

**Comment by shk3bq4d** [comment]
ok, I've opened PR #89 as a proposal to fix this issue
