### ISSUE TITLE
Make all default rules (NTP, DNS, etc.) configurable

### ISSUE THREAD

**Issue by huangyg11** [geerlingguy/ansible-role-firewall#9]
I use this role in my project. I find it adding a ntp rule on output chain. I ignored it at first. 

Lately, my memcache get slowly on the server. I spent lots of hours and finally I find it is because of the rule on the iptables' output chain.

I haven't dig out why the rule has such effect.  But I am sure it is because of it. Please remove it.

**Comment by geerlingguy** [comment]
Since 99.9% of my servers require that rule, I don't want to remove it entirely (forcing all playbooks to then define it later), but I would like to make that, and port 53, configurable.

**Comment by lots0logs** [comment]
Any updates on this? I notice currently the rules for NTP are universal so they work for servers and clients. Seems to me that more often than not the system in use will function only as a NTP client and not as a NTP server. Ideally there would be an easy way to specify NTP client, server, or both and have the rules adjusted accordingly. 

NTP Client:
```
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
```
(incoming is covered by the ESTABLISHED,RELATED state rule)

NTP Server:
```
iptables -A INPUT -p udp --sport 123 -j ACCEPT
```
(all output is allowed anyway)

NTP Client & Server:
```
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A INPUT -p udp --sport 123 -j ACCEPT
```
