### ISSUE TITLE
Add Default Policy Option

### ISSUE THREAD

**Issue by mthbrown** [geerlingguy/ansible-role-firewall#93]
Hi,

I really like this role but one thing I feel missing is that you can't set the default policy for a given table and interface (you'd have to do so custom `additional_rules`). It's be great if this was an option without requiring custom `iptables` rules. Thanks

**Comment by soflane** [comment]
+1 for this issue

(and many thanks for your ansible tutorials and roles !!)

Greetings from Belgium
